/*Game Sounds By Faff */
/*All sounds hosted by Faff (forever)  */

#include <a_samp>

/* Game sound effects */
monsterkillsound(playerid) //Play sound: Monsterkill
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/w0q328dwei6l3jw/monsterkill.wav");
}
megakillsound(playerid)//Play sound: Megakill
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/8geodww8rpiv5qx/multikill.wav");
}
deathsound(playerid)//Play sound: *Screaming human*
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/8379jhis0axxtpk/humiliation.wav");
}
godlikesound(playerid)//Play sound: Godlike
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/jqistvys6tsv7uu/godlike.wav");
}
holyshitsound(playerid)//Play sound: Holyshit
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/exys8ostmyzrstk/holyshit.wav");
}
ownagesound(playerid)//Play sound: ownage
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/qjuq5jqou6hdbgq/oneandonly.wav");
}
firstbloodsound(playerid)//Play sound: First blood
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/i8qmefbtr7pqn35/prepare.wav");
}
scaryscreamsound(playerid)//Play sound: *scary screaming human*
{
PlayAudioStreamForPlayer(playerid, "https://dl.dropboxusercontent.com/s/1ob3nu3pzn4fucv/maytheforce.wav");
}
/* Game Sound Effects */